#!/bin/bash

# Pull photos off my external usb drive using rsync.
#
# TODO:
# - add ability to specify "backup to external" vs "pull from external"
#
# 2019.10.02 add to git, update variable names for clarity
# jan 2019   updated for pull
# dec 2015   init

driveUSB="/cygdrive/d"
driveLocal="/cygdrive/q"

src="${driveUSB}/photo-bkup/photos/"
dst="${driveLocal}/photos/"

rsyncCmd="rsync -rltDP $src $dst"

echo -e "\nBacking up photos..."
echo -e "\n\tsource is: $src"
echo -e "\tdestination is: $dst"

echo -e "\nRunning command: $cmd"

$cmd

echo -e "\nAll done!\n"

